console.log("HELLO WORLD..")
console.log("this code is running...")
console.log("thiscode is also running")
console.log("this code is running like a wow")
console.log("so beautiful , so elegant just loooking like a supra hehehe")